language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm --notest Class::Accessor
  - cpanm --notest Devel::Cover
  - cpanm --notest Modern::Perl
  - cpanm --notest Config::Merge
  - cpanm --notest XML::Simple
  - cpanm --notest Net::Server::PreFork
install:
  - prove -v --timer
  - cover
notifications:
  recipients:
    - chris@bigballofwax.co.nz
  email:
    on_success: change
    on_failure: always
